version: '3'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
  edv:
    image: or13/edv:latest
    ports:
      - '8080:8080'
    env_file:
      - ./environment/prod.env
